name: Docker Image CI

on:
  push:
    branches: [ "vega/release/25.0.4" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build Keycloak
      uses: ./.github/actions/build-keycloak
      with:
        upload-m2-repo: false
        upload-dist: true
    - name: Copy Docker image
      working-directory: ./quarkus
      run: cp ./dist/target/keycloak-25.0.4.tar.gz ./container
    - name: Build the Docker image
      working-directory: ./quarkus/container
      run: docker build --build-arg KEYCLOAK_DIST=keycloak-25.0.4.tar.gz -t jstale/keycloak:test .
      
    - name: Login to dockerhub
      uses: docker/login-action@v3.3.0
      with:
       username: ${{ secrets.DOCKER_HUB_USERNAME }}
       password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - name: Build the Docker image
      run: docker push jstale/keycloak:test
       
